name: test

on: [pull_request, push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox -e lint
        run: tox
        env:
          TOXENV: lint

  test:
    name: unittests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py37-dj22
            - py37-dj32
            - py39-dj22
            - py39-dj32
            - py39-dj40
            - py39-dj41
            - py39-dj42
            - py310-dj50
        include:
          - toxenv: py37-dj22
            python-version: 3.7
          - toxenv: py37-dj32
            python-version: 3.7
          - toxenv: py39-dj22
            python-version: 3.9
          - toxenv: py39-dj32
            python-version: 3.9
          - toxenv: py39-dj40
            python-version: 3.9
          - toxenv: py39-dj41
            python-version: 3.9
          - toxenv: py39-dj42
            python-version: 3.9
          - toxenv: py310-dj50
            python-version: '3.10'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}

      - name: Store test coverage
        if: matrix.toxenv != 'lint'
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: .coverage.*

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Retrieve test coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage

      - name: Check coverage
        run: tox -e coverage
